<<script type="text/javascript">

document.getElementById('home').style.color = '#cc9900'; 
document.getElementById('home').style.font.weight = 'bold';
</script>

<div id="content" class="clearfix">
	<h3 class="yellow f14">Bem-Vindo</h3>
	<p>Trabalhando com profissionais qualificados e metodologias de ponta,
		a Avante Consultoria em TI oferece a sua empresa serviços e
		consultorias na área de tecnologia da informação com o que há
		de melhor e mais recente no mercado. Dentre os vários serviços
		prestados, estão presentes treinamentos, consultorias, alocações de
		profissionais In Company e desenvolvimento de software e websites.
		Deixe a Avante Consultoria surpreender você!</p>
</div>
