
<script type="text/javascript">
    document.getElementById('clientesmenu').style.color = '#cc9900'; 
    document.getElementById('clientesmenu').style.font.weight = 'bold';
    
    function cep(cep2, urlbase){
    	$.ajax({
  		  	  url: 'http://localhost/prog_web/public/cliente.ajax.php',
    		  type: 'POST',
    		  data: { cep:cep2},
    		  success:function(Req) {
        		  var array = Req.split('-');
        		  if(array[0] == 0){
        			  $("#cep_invalido").show();
	        		  $("#c_estado").val('');
	        		  $("#c_cidade").val('');
	        		  $("#c_endereco").val('');
        		  }else{
	        		  $("#c_estado").val(array[5]);
	        		  $("#c_cidade").val(array[4]);
	        		  $("#c_endereco").val(array[3]+' '+array[1]+' '+array[2]);
        			  $("#cep_invalido").hide();
        		  }
        		  
    		  },
		  });
    }
</script>

<div id="content" class="clearfix">
    <form name="formulario" method="post" action="<?php echo $this->url(array('controller'=>'cliente','action'=>'cadastro'));?>" id="formulario">
        <table align="center" border="0" cellspacing="0" cellpadding="0" >
            <tbody>
                <tr>
                    <td class="table_nome">
                        Nome :
                    </td>
                    <td>
                       <input type="text" name="cli_nome" id="c_nome" value="" size="40" />
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        Email : 
                    </td>
                    <td>
                        <input type="text" name="cli_email" id="c_email" value=" " size="40" />
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        CPF : 
                    </td>
                    <td>
                        <input type="label" name="cli_cpf" id="c_cpf" value="" size="40" />
                    </td>                  
                </tr>
                <tr>
                    <td class="table_nome">
                        Sexo:                      
                    </td>
                    <td>
                        <label>
                            <input type="radio" name="cli_sexo" id="c_sexo" value="M" />
                            Masculino
                        </label>
                        <label> 
			<input  type="radio" name="cli_sexo " id="c_sexoF" value="F" />
                            Feminino
                        </label>
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        CEP: 
                    </td>
                    <td>
                        <input type="text" name="cli_cep" id="c_cep" value="" onblur="cep(this.value, '<?php echo $this->baseUrl(); ?>');" size="10" />
                    	<div id="cep_invalido" name="cep_invalido" style="display: none;">CEP Inv·lido!</div>
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        Estado: 
                    </td>
                    <td>
                       <input type="text" name="cli_estado" id="c_estado" value="" size="20"  />     
                    </td>    
                </tr>   
                <tr>
                    <td class="table_nome">
                        Cidade: 
                    </td>
                    <td>
                       <input type="text" name="cli_cidade" id="c_cidade" value="" size="20"  />    
                    </td>    
                </tr>  
                <tr>
                    <td class="table_nome">
                        Endere√ßo: 
                    </td>
                    <td>
                       <input type="text" name="cli_endereco" id="c_endereco" value="" size="60"   />   
                    </td>    
                </tr>
                <tr>
                    <td class="table_nome">
                    </td>
                    <td>
                        <input type="submit" value="Cadastrar" />  
                    </td>    
                </tr>
            </tbody> 
        </table>
    </form> 
</div>