<script type="text/javascript">
    document.getElementById('usuariomenu').style.color = '#cc9900'; 
    document.getElementById('usuariomenu').style.font.weight = 'bold';
</script>

<div id="content" class="clearfix">
    <form name="formulario" method="post" action="<?php echo $this->url(array('controller'=>'cliente','action'=>'editar'));?>" id="formulario">
        <table align="center" border="0" cellspacing="0" cellpadding="0" >
   
            <tbody>
               <tr>
                    <td class="table_nome">
                         Codigo :
                    </td>
                    <td>
                        <input type="hidden" name="cli_id" value="<?php echo $this->cliente_id?>">
                        <input type="text" name="cli_id_vis" id="c_nome" value="<?php echo $this->cliente_id?>" size="3" disabled />
                    </td>    
               </tr>            
                <tr>
                   <td class="table_nome">
                         Nome :
                    </td>
                    <td>
                       <input type="text" name="cli_nome" id="c_nome" value="<?php echo $this->cliente_nome?>" size="40" />
                    </td>
                </tr>
                 <tr>
                    <td class="table_nome">
                        Email : 
                    </td>
                    <td>
                        <input type="text" name="cli_email" id="c_email" value="<?php echo $this->cliente_Email?>" size="40" />
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        CPF : 
                    </td>
                    <td>
                        <input type="label" name="cli_cpf" id="c_cpf" value="<?php echo $this->cliente_cpf?>" size="40" />
                    </td>                  
                </tr>
                <tr>
                    <td class="table_nome">
                        Sexo:                      
                    </td>
                    <td>
                        <?php 
                            $checkedM = "";
                            $checkedF = "";

                            if($this->cliente_sexo == "M"){
                                    $checkedM = "checked";			
                            }
                            else
                                if($this->cliente_sexo == "F"){				
                                    $checkedF = "checked";
                                }
                        ?>                        
                        <input type="radio" name="cli_sexo" id="c_sexoM" value="M" <?php echo $checkedM;?>/>
                        <label>
                              Masculino                    
                        </label>
			<input type="radio" name="cli_sexo" id="c_sexoF" value="F" <?php echo $checkedF;?> />
                        <label> 
                            Feminino
                        </label>
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        CEP: 
                    </td>
                    <td>
                        <input type="text" name="cli_cep" id="c_cep" value="<?php echo $this->cliente_cep?>"  size="10" />
                    </td>
                </tr>
                <tr>
                    <td class="table_nome">
                        Estado: 
                    </td>
                    <td>
                       <input type="text" name="cli_estado" id="c_estado" value="<?php echo $this->cliente_estado?>" size="20"  />     
                    </td>    
                </tr>   
                <tr>
                    <td class="table_nome">
                        Cidade: 
                    </td>
                    <td>
                       <input type="text" name="cli_cidade" id="c_cidade" value="<?php echo $this->cliente_cidade?>" size="20"  />    
                    </td>    
                </tr>  
                <tr>
                    <td class="table_nome">
                        Endereço: 
                    </td>
                    <td>
                       <input type="text" name="cli_endereco" id="c_endereco" value="<?php echo $this->cliente_endereco?>" size="40"   />   
                    </td>    
                </tr>
                <tr>
                    <td class="table_nome">
                    </td>
                    <td>
                        <input type="submit" value="Alterar" />  
                    </td>    
                </tr>  
            </tbody> 
        </table>
    </form> 
</div>