<script type="text/javascript">
document.getElementById('contatomenu').style.color = '#cc9900'; 
document.getElementById('contatomenu').style.font.weight = 'bold';
</script>

<div id="content" class="clearfix">
 <h3 class="yellow f14">Contato</h3>
  <p>Conheça a Avante TI e surpreenda-se:<br></br>

AVANTE TI CONSULTORIA em TECNOLOGIA<br></br>

RUA JOAQUIM SOUZA, N. 222 – SALA 99<br></br>
BAIRRO JARDIM DAS ARAUCARIAS – CEP: 78.048-000 – CUIABÁ-MT<br></br>
SKYPE: avanteti<br></br>
E-MAIL: contato@avanteti.com.br</p><br></br>
   
Entre e contato conosco:</p><br></br>

  <form name="formulario_contato" method="post" action="" id="formulario_contato">
 	Nome: <input type="text" name="nome" id="nome_contato" value="" placeholder ="Seu nome"/> <br> </br>
  Email: <input type="text" name="email" id="email_contato" value="" placeholder="Seu e-mail" /> </br>
  <input type="submit" value="Enviar Mensagem" onclick="alert('Enviado com Sucesso');" />
  </form>
  <textarea rows="4" cols="50" name="descricao" form="formulario_contato">
Digite seu texto Aqui...</textarea>
 	  

</div>